# Generated by Django 6.1 on 2026-08-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Raw User-Agent header — used for login/device history.', max_length=500),
        ),
    ]
