# Generated by Django 6.1 on 2026-08-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_logs', '0002_auditlog_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(blank=True, default=dict, help_text='The submitted request body for this mutation, with sensitive fields (password/token/otp_code/api keys/...) redacted. Captures intent, not a computed diff.'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, help_text="Best-effort — the trailing numeric ID in the URL path (e.g. '42' for /api/appointments/42/).", max_length=50),
        ),
    ]
