# Generated by Django 6.1 on 2026-08-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_medicalrecord_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosis',
            options={'ordering': ['-diagnosed_at']},
        ),
    ]
