# Generated by Django 6.1 on 2026-08-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labreport',
            options={'ordering': ['-uploaded_at']},
        ),
    ]
