# Generated by Django 6.1 on 2026-08-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appt_doctor_date_idx_and_more'),
        ('doctors', '0002_alter_doctor_options'),
        ('laboratory', '0002_alter_labreport_options'),
        ('patients', '0002_alter_patient_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['status'], name='labtest_status_idx'),
        ),
    ]
