# Generated by Django 6.1 on 2026-08-12 09:34

import ai_healthcare_triage_appointment_system.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labtest_labtest_status_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), ai_healthcare_triage_appointment_system.validators.MaxFileSizeValidator(10)]),
        ),
    ]
