# Generated by Django 6.1 on 2026-08-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('departments', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text='If off, triage skips the LLM summary and returns only the rule-based result.')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama (Local)'), ('groq', 'Groq (Cloud)')], default='ollama', max_length=20)),
                ('ollama_base_url', models.CharField(default='http://127.0.0.1:11434', max_length=255)),
                ('ollama_model', models.CharField(default='qwen2.5:7b', max_length=100)),
                ('groq_api_key', models.CharField(blank=True, help_text='Stored in plaintext for this MVP — move to a secrets manager before production.', max_length=255)),
                ('groq_model', models.CharField(default='llama-3.1-8b-instant', max_length=100)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider Settings',
                'verbose_name_plural': 'AI Provider Settings',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('respiratory', 'Respiratory'), ('cardiac', 'Cardiac'), ('neurological', 'Neurological'), ('gastrointestinal', 'Gastrointestinal'), ('dermatological', 'Dermatological'), ('dental', 'Dental'), ('ophthalmological', 'Ophthalmological'), ('musculoskeletal', 'Musculoskeletal'), ('mental_health', 'Mental Health'), ('ent', 'Ear/Nose/Throat'), ('gynecological', 'Gynecological')], default='general', max_length=30)),
                ('keywords', models.CharField(help_text='Comma-separated synonyms/phrases used for matching.', max_length=500)),
                ('severity_weight', models.PositiveIntegerField(default=1, help_text='1 (mild) - 5 (severe) contribution to the urgency score.')),
                ('red_flag', models.BooleanField(default=False, help_text='If matched, triage is escalated straight to Emergency.')),
                ('suggested_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='symptoms', to='departments.department')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms_text', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('emergency', 'Emergency')], max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('ai_provider_used', models.CharField(blank=True, max_length=20)),
                ('ai_summary_error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assessments', to='appointments.appointment')),
                ('detected_symptoms', models.ManyToManyField(blank=True, related_name='assessments', to='triage.symptom')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='patients.patient')),
                ('suggested_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_assessments', to='departments.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
