# Generated by Django 6.1 on 2026-08-11 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('emergency', 'Emergency')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('emergency_numbers', models.CharField(blank=True, help_text="e.g. 'Pakistan: 1122 (Rescue), 15 (Police)'", max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Emergency guidance',
            },
        ),
        migrations.RemoveField(
            model_name='aiprovidersettings',
            name='groq_api_key',
        ),
        migrations.AddField(
            model_name='aiprovidersettings',
            name='groq_api_key_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted at rest (Fernet, key derived from DJANGO_SECRET_KEY).'),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='clinician_agrees',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='clinician_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triageassessment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to='doctors.doctor'),
        ),
    ]
