# Generated by Django 6.1 on 2026-08-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_emergencyguidance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyguidance',
            options={'ordering': ['urgency'], 'verbose_name_plural': 'Emergency guidance'},
        ),
    ]
