# Generated by Django 6.1 on 2026-08-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_appt_doctor_date_idx_and_more'),
        ('departments', '0001_initial'),
        ('doctors', '0002_alter_doctor_options'),
        ('patients', '0002_alter_patient_options'),
        ('triage', '0003_alter_emergencyguidance_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='triageassessment',
            index=models.Index(fields=['urgency'], name='triage_urgency_idx'),
        ),
    ]
