# Generated by Django 6.1 on 2026-08-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_triageassessment_triage_urgency_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='triageassessment',
            name='ai_summary_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('ready', 'Ready'), ('failed', 'Failed')], default='not_requested', help_text='The rule-based result above is always immediate; the AI summary is generated in the background (Celery) so a slow/unreachable LLM never blocks the triage response.', max_length=20),
        ),
    ]
