# Generated by Django 6.1 on 2026-08-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitalfaq',
            options={'ordering': ['id'], 'verbose_name': 'Hospital FAQ', 'verbose_name_plural': 'Hospital FAQs'},
        ),
    ]
