# Generated by Django 6.1 on 2026-08-12 09:34

import ai_healthcare_triage_appointment_system.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='message_attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx']), ai_healthcare_triage_appointment_system.validators.MaxFileSizeValidator(10)]),
        ),
    ]
