# Generated by Django 6.1 on 2026-08-12 04:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_consultation_completed_at_and_more'),
        ('doctors', '0002_alter_doctor_options'),
        ('patients', '0002_alter_patient_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'appointment_date'], name='appt_doctor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', '-appointment_date'], name='appt_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='waitlist',
            index=models.Index(fields=['doctor', 'preferred_date', 'status'], name='wl_doctor_date_status_idx'),
        ),
    ]
